version: '2'
services:
  postgres-db:
    container_name: postgres-db
    restart: on-failure
    image: postgres:latest
    volumes:
      - ./build/package/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_DB: ${PGDBNAME}
    ports:
      - 5432:5432
  stan:
    container_name: stan
    restart: on-failure
    image: nats-streaming:latest
    ports:
      - 4222:4222
      - 8222:8222
    command:
      - "--cluster_id"
      - ${STANCLID}
  show-order:
    container_name: show-order
    build: ./
    ports:
      - 8080:${RESTPORT}
    links:
      - postgres-db:database
      - stan
    depends_on:
      - postgres-db
      - stan
    env_file:
      - ./deployments/.env
